apiVersion: kafka.upjet.crossplane.io/v1alpha1
kind: Topic
metadata:
  name: example
spec:
  forProvider:
    name: topic.name
    replicationFactor: 1
    partitions: 2
    config:
      min.insync.replicas: "1"

