apiVersion: kafka.upjet.crossplane.io/v1alpha1
kind: UserScramCredential
metadata:
  name: user1
spec:
  forProvider:
    username: user1
    scramMechanism: SCRAM-SHA-256
    passwordSecretRef:
      name: user1-secret
      namespace: upbound-system
      key: password

---
apiVersion: v1
kind: Secret
metadata:
  name: user1-secret
  namespace: upbound-system
type: Opaque
stringData:
  password: "correcthorsebatterystaple"